version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
#      - html-data:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: sis_devops
      POSTGRES_DB: bd_devops
      POSTGRES_USER: sis_devops
      PGDATA: /var/lib/pg/13
    volumes:
      - pgsql-data:/var/lib/pg/13
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgsql-data:
    driver: local
  html-data:
    driver: local
